### ISSUE TITLE
https://coder.social/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/issues/36

### ISSUE THREAD

**Issue by thienbui** [FeitianSmartcardReader/R502_SDK_Latest#2]
this error occuring when using ft.readerFind() in latest Android versions

```
W/System.err: java.lang.Exception: java.lang.IllegalArgumentException: uz.newtech.mobilkassa: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err:     at com.ftsafe.comm.CommBase.readerFind(CommBase.java:205)
W/System.err:     at com.ftsafe.readerScheme.FTReader.readerFind(FTReader.java:30)
```
Thanks

**Comment by FeitianSmartcardReader** [comment]
latest SDK already fix it.
